spring:
  output:
    ansi:
      enabled: always
  config:
    import: 'optional:configserver:'
  datasource:
    url: jdbc:postgresql://localhost:5432/notification
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://vsofjkut:WWJY_EeQVli0IQadxcv_YwBOqQcSsxv9@stingray.rmq.cloudamqp.com/vsofjkut

server:
  compression:
    enabled: true
  port: 8182
  servlet:
    context-path: /ead-notification
  forward-headers-strategy: framework

logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health

ead:
  broker:
    exchange:
      notificationCommandExchange: ead.notification.command
      queue:
        notificationCommandQueue:
          name: ead.notification.command.ms.notification
      key:
        notificationCommandKey: ms.notification