logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

server:
  port: ${PORT}

spring:
  output:
    ansi:
      enabled: always

ead:
  database:
    url: ${DATABASE_CONN}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  broker:
    connection:
      address: ${CLOUDAMQP_URL}
    exchange:
      notification-command-exchange: ead.notification.command
      queue:
        notification-command-queue:
          name: ead.notification.command.ms.notification
      key:
        notification-command-key: ms.notification

management:
  endpoints:
    web:
      exposure:
        include:
          - refresh
          - health